export declare function get__jwks__json(): Promise<any>;
export declare function get__userinfo__auth0(): any;
export declare function post__signup__dbconnections__auth0(body: any): any;
export declare function post__start__passwordless__auth0(body: any): any;
export declare function post__change_password__auth(password: any): Promise<any>;
export declare function post__change_password__dbconnections__auth0(body: any): any;
export declare function post__token__oauth__auth0(body: any): any;
export declare function _authorization__header__access_token__verify(token__auth0: any): string | false;
export declare function _authorization__header__access_token(token__auth0: any): string | false;
export declare function validate__current__token__auth0(token__auth0: any): Promise<void>;
export declare function _authorization__header__id_token__verify(token__auth0: any): Promise<string>;
export declare function _body__password_realm(...form: any[]): any;
export declare function _body(...form: any[]): any;
