export declare function trigger__event__native(el: any, name__event: any): void;
export declare function trigger__event__custom(el: any, name__event: any, data: any): void;
declare type Params__MouseEvent = {
    bubbles?: boolean;
    cancelable?: boolean;
    view?: any;
    detail?: number;
    screenX?: number;
    screenY?: number;
    clientX?: number;
    clientY?: number;
    ctrlKey?: boolean;
    altKey?: boolean;
    shiftKey?: boolean;
    metaKey?: boolean;
    button?: number;
    relatedTarget?: any;
};
export declare function _MouseEvent(eventType: any, params?: Params__MouseEvent): MouseEvent;
export {};
