export declare const a1__month: string[];
export declare const a1__month__abbrev: string[];
export declare const minute: number;
export declare const hour: number;
export declare const day: number;
export declare const week: number;
export declare function _yyyymmddhhmmss(date?: any): string;
export declare function _yyyymmdd(date?: any): string;
export declare function _yyyymmddhhmmss__utc(date?: any): string;
export declare function _yyyymmdd__utc(date?: any): string;
export declare function _mm_yyyy(date?: any): string;
export declare function _mm_yyyy__utc(date?: any): string;
export declare function _MM_yyyy(date?: any): string;
export declare function _MM_yyyy__utc(date?: any): string;
export declare function _M_yyyy(date?: any): string;
export declare function _M_yyyy__utc(date?: any): string;
export declare function _m_yy(date?: any): string;
export declare function _m_yy__utc(date?: any): string;
export declare function format__date__prose(date?: any): string;
export declare function format__date__prose__utc(date?: any): string;
export declare function toLocalDateString(date?: Date): string;
export declare function _date(...arg_a1: []): Date;
export declare function _date__append__local_tz(txt__date: any): Date;
export declare function _date__at(time: any): Date;
export declare function _date__diff(diff: any): Date;
export declare function _milliseconds(date?: Date): number;
export declare function _seconds(date?: Date): number;
