packages:
  - ../../packages/a__target
  - ../../packages/array
  - ../../packages/assert
  - ../../packages/atob
  - ../../packages/auth0
  - ../../packages/auth0-lock
  - ../../packages/auth0-management
  - ../../packages/auth0-ui
  - ../../packages/aws-cli
  - ../../packages/babel
  - ../../packages/base16
  - ../../packages/btoa
  - ../../packages/cache
  - ../../packages/carousel
  - ../../packages/chain
  - ../../packages/child_process
  - ../../packages/class
  - ../../packages/cli-args
  - ../../packages/clipboard
  - ../../packages/cognito
  - ../../packages/color
  - ../../packages/color-bar
  - ../../packages/combinators
  - ../../packages/cookie
  - ../../packages/core-js
  - ../../packages/csv
  - ../../packages/currency
  - ../../packages/data
  - ../../packages/date
  - ../../packages/debounce
  - ../../packages/dialog
  - ../../packages/dir
  - ../../packages/disqus
  - ../../packages/dist
  - ../../packages/dom
  - ../../packages/drip_marketing
  - ../../packages/email
  - ../../packages/env
  - ../../packages/error
  - ../../packages/esm
  - ../../packages/etag
  - ../../packages/etsy
  - ../../packages/etsy_cache
  - ../../packages/event
  - ../../packages/fb
  - ../../packages/fetch
  - ../../packages/fibonacci
  - ../../packages/file-reader
  - ../../packages/flash
  - ../../packages/font
  - ../../packages/fontawesome
  - ../../packages/form
  - ../../packages/function
  - ../../packages/functional
  - ../../packages/google
  - ../../packages/graphql
  - ../../packages/graphql-client
  - ../../packages/graphql-service
  - ../../packages/highlight.js
  - ../../packages/html
  - ../../packages/http
  - ../../packages/iex
  - ../../packages/iex-graphql
  - ../../packages/instagram
  - ../../packages/instagram_cache
  - ../../packages/isomorphic-fetch
  - ../../packages/jetbrains
  - ../../packages/jsdoc
  - ../../packages/jwt
  - ../../packages/keyboard
  - ../../packages/layer
  - ../../packages/lerna
  - ../../packages/loader
  - ../../packages/local-storage
  - ../../packages/logger
  - ../../packages/markdown
  - ../../packages/math
  - ../../packages/matrix
  - ../../packages/module-card
  - ../../packages/monorepo
  - ../../packages/nav
  - ../../packages/number
  - ../../packages/object
  - ../../packages/package
  - ../../packages/pagination
  - ../../packages/papaparse
  - ../../packages/pipe
  - ../../packages/polarity
  - ../../packages/polka-types
  - ../../packages/postgres
  - ../../packages/queue
  - ../../packages/random
  - ../../packages/regex
  - ../../packages/ribbon
  - ../../packages/ripple-effect
  - ../../packages/rollup
  - ../../packages/route
  - ../../packages/s3
  - ../../packages/sapper
  - ../../packages/sapper-amp
  - ../../packages/sass
  - ../../packages/sass-build
  - ../../packages/scroll
  - ../../packages/search
  - ../../packages/security
  - ../../packages/session
  - ../../packages/set
  - ../../packages/shell
  - ../../packages/sleep
  - ../../packages/socicon
  - ../../packages/ssh
  - ../../packages/store
  - ../../packages/string
  - ../../packages/strip__logger
  - ../../packages/style
  - ../../packages/svelte
  - ../../packages/svelte-transitions
  - ../../packages/svg
  - ../../packages/switch
  - ../../packages/table
  - ../../packages/test
  - ../../packages/theme
  - ../../packages/theme--pocketgrid
  - ../../packages/time
  - ../../packages/touch
  - ../../packages/tradingview
  - ../../packages/tree__checkbox
  - ../../packages/uikit
  - ../../packages/up__apex
  - ../../packages/uri
  - ../../packages/uuid
  - ../../packages/version__app
  - ../../packages/version__obj
  - ../../packages/webgl
  - ../../packages/window
  - ../../packages/word-segmentation
  - ../../tools/dev-tools
  - ../../tools/git-tools
  - ../../tools/package-tools
  - ../../tools/rush-tools
  - ../../tools/typescript-tools
