import "babel-polyfill";
import riot from "riot";
global.riot = riot;
import "../dom/ctx.tag";
import "../dom/ctx-size.tag";
import "../quovo/agent";
import "../quovo/quovo-sync-iframe.tag";
import "./window.onmessage.quovo";
import "./quovo-demo.tag";
import "../quovo/quovo-users-tile.tag";
import "../quovo/quovo-users-navigation.tag";
import "../quovo/quovo-users.tag";
import "../quovo/quovo-user-tile.tag";
import "../quovo/quovo-user-navigation.tag";
import "../quovo/quovo-user-accounts.tag";
import "../quovo/quovo-user-account-tile.tag";
import "../quovo/quovo-user-account-navigation.tag";
import "../quovo/quovo-user-account-details.tag";
import "../quovo/quovo-account-portfolios.tag";
import "../quovo/quovo-portfolio-tile.tag";
import "../quovo/quovo-portfolio-navigation.tag";
import "../quovo/quovo-portfolio-details.tag";
import "../quovo/quovo-portfolio-history.tag";
import "../quovo/quovo-positions.tag";
import "../quovo/quovo-user-details.tag";