export const tran_type$map = {
	ACFE: 'Account Fee',
	ADFE: 'Administrative Fee',
	ADJU: 'Adjustment',
	ALFE: 'Actuarial Fee',
	APFE: 'Appraisal Fee',
	ASSN: 'Assignment',
	BTC: 'Buy to Close',
	BTCC: 'Buy to Close Call',
	BTCP: 'Buy to Close Put',
	BTO: 'Buy to Open',
	BTOC: 'Buy to Open Call',
	BTOP: 'Buy to Open Put',
	BUYL: 'Buy Long',
	BUYS: 'Buy Short',
	CTFE: 'Contract Fee',
	CTRB: 'Contribution',
	DEPO: 'Deposit',
	DPFC: 'Dividend Paid From Cash',
	DTRB: 'Distribution',
	DV2C: 'Dividend',
	FNFE: 'Fund Fee',
	FTAX: 'Foreign Tax',
	FTXW: 'Foreign Tax Withheld',
	IP2C: 'Interest',
	IPFC: 'Interest Paid From Cash',
	IREC: 'Interest Receivable',
	ISRV: 'Interest Reinvestment',
	LG2C: 'Long-term Capital Gain to Cash',
	LGFE: 'Legal Fee',
	LGRV: 'Long-term Capital Gain Reinvestment',
	LPMT: 'Loan Payment',
	MCFE: 'Miscellaneous Fee',
	MERG: 'Merge',
	MEXP: 'Margin Expense',
	MGFE: 'Management Fee',
	NQDV: 'Non-qualified Dividend',
	NTAX: 'Non-resident Tax',
	QUDV: 'Qualified Dividend',
	REIN: 'Dividend Reinvestment',
	RTOP: 'Return of Principal',
	SASS: 'Sell Assigned',
	SDTB: 'Stock Distribution',
	SELL: 'Sell',
	SG2C: 'Short-term Capital Gain to Cash',
	SGRV: 'Short-term Capital Gain Reinvestment',
	SPIN: 'Spin Off',
	SPLT: 'Split',
	STC: 'Sell to Close',
	STCC: 'Sell to Close Call',
	STCP: 'Sell to Close Put',
	STO: 'Sell to Open',
	STOC: 'Sell to Open Call',
	STOP: 'Sell to Open Put',
	STXW: 'State Tax Withheld',
	TAXW: 'Tax Withheld',
	TDFE: 'Trading Fee',
	TRFE: 'Transfer Fee',
	TUFE: 'Trust Fee',
	UG2C: 'Unqualified Gain to Cash',
	WITH: 'Withdrawal',
	XFER: 'Transfer',
	XPRD: 'Expired',
	XRCS: 'Exercise (Option)'
}